# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
