# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='course',
            field=models.CharField(choices=[('SE', 'Software Engineering'), ('BIS', 'Business Information Systems'), ('DBMS', 'Database Management Systems'), ('TC', 'Technical Communication'), ('CN', 'Computer Networks'), ('LP', 'Language Processors')], max_length=50, verbose_name='Some choices...'),
        ),
    ]
