# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170411_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='course',
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.RegisterStudent'),
        ),
    ]
