# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_registerstudent_baddr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerstudent',
            old_name='baddr',
            new_name='bluetooth_addr',
        ),
    ]
